apiVersion: batch/v1
kind: Job
metadata:
  name: iam-s3
spec:
  template:
    metadata:
      labels:
        app: iam-s3
    spec:
      serviceAccountName: jalsule1
      containers:
      - name: eks-iam-test
        image: amazon/aws-cli:latest
        args: ["s3", "ls", "s3://s3test-jsule"]
      restartPolicy: Never
