kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: read-service
  namespace: lab4
subjects:
- kind: ServiceAccount
  name: jalsule1 #service account
  #apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: service-reader
  apiGroup: rbac.authorization.k8s.io