apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: service-reader
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["list","get","watch"]
  
- apiGroups: [""]
  verbs: ["get", "list", "watch"]
  resources: ["services"]