apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::867152996688:role/eksctl-assignment4jsule-nodegroup-NodeInstanceRole-1CZ65IIKVVYDG
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:mapRoles: {}
    manager: vpcLambda
    operation: Update
    time: "2022-08-11T16:46:31Z"
  name: aws-auth
  namespace: kube-system
data:
  mapUsers: |
    - userarn: arn:aws:iam::867152996688:user/jsule
      username: jsule
